task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  persistent_worker:
  isolation:
    container:
      image: ubuntu:20.04
      cpu: 24
      memory: 128G

 name: Download and upload video
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests
    - curl -o script.py https://example.com/script.py
    - python3 script.py
